import { getCanonicalUrl } from '../lib/site-url.ts'
import type { CanonicalRoute, CanonicalRouteInput, RouteId } from './types.ts'

const plannedRouteState = {
  implementationStatus: 'planned',
  publicationStatus: 'planned',
  indexability: 'indexable',
} as const

function defineRoute(route: CanonicalRouteInput): CanonicalRoute {
  return {
    ...route,
    canonicalUrl: getCanonicalUrl(route.path),
  }
}

/**
 * The complete target route inventory. Consumers must filter by lifecycle state
 * before publishing navigation or sitemap entries; only `/` exists today.
 */
export const routeRegistry = [
  defineRoute({
    id: 'home',
    path: '/',
    pageType: 'home',
    parentId: null,
    primaryKeyword: 'lawn care des moines ia',
    secondaryKeywords: [
      'lawn care service Des Moines',
      'lawn maintenance Des Moines',
      'lawn care company Des Moines',
      'residential lawn care Des Moines',
      'property services Des Moines',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Lawn Care & Snow Removal in Des Moines, IA | Mo's Lawn Care",
    h1: 'Lawn Care & Snow Removal in Des Moines, IA',
    description:
      'Professional lawn care, mowing, landscaping, cleanups, aeration, weed control and snow removal for homes and businesses in the Des Moines metro.',
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['service-areas', 'about', 'our-work', 'reviews', 'contact', 'blog'],
    outboundLinkIds: [
      'services',
      'commercial-property-services',
      'service-areas',
      'service-area-ankeny',
      'service-area-waukee',
      'service-area-norwalk',
      'service-area-altoona',
      'about',
      'our-work',
      'reviews',
      'contact',
      'blog',
    ],
  }),
  defineRoute({
    id: 'services',
    path: '/services',
    pageType: 'services-index',
    parentId: 'home',
    primaryKeyword: 'lawn care services des moines ia',
    secondaryKeywords: [
      'lawn maintenance services Des Moines',
      'yard maintenance Des Moines',
      'landscaping and lawn care Des Moines',
      'seasonal lawn services Des Moines',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Lawn Care Services in Des Moines, IA | Mo's Lawn Care",
    h1: 'Lawn Care Services for Des Moines Properties',
    description:
      "Explore Mo's Lawn Care services in Des Moines, including mowing, aeration and seeding, weed control, landscaping, cleanups, grading and snow removal.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['home'],
    outboundLinkIds: [
      'service-lawn-mowing',
      'service-aeration-overseeding',
      'service-fertilization-weed-control',
      'service-landscaping',
      'service-flower-bed-maintenance',
      'service-yard-cleanup',
      'service-spring-cleanup',
      'service-fall-cleanup-leaf-removal',
      'service-grading',
      'service-snow-removal',
      'commercial-property-services',
      'service-areas',
      'contact',
    ],
  }),
  defineRoute({
    id: 'service-lawn-mowing',
    path: '/services/lawn-mowing',
    pageType: 'service',
    parentId: 'services',
    primaryKeyword: 'lawn mowing des moines ia',
    secondaryKeywords: [
      'lawn mowing service Des Moines',
      'grass cutting service Des Moines',
      'residential lawn mowing Des Moines',
      'lawn maintenance Des Moines',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Lawn Mowing Service in Des Moines, IA | Mo's Lawn Care",
    h1: 'Lawn Mowing Service in Des Moines, IA',
    description:
      "Keep your property sharp with professional lawn mowing in Des Moines, IA. Residential and commercial service available. Request a free estimate from Mo's.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['home', 'services', 'article-how-often-to-mow-lawn-iowa'],
    outboundLinkIds: [
      'service-aeration-overseeding',
      'service-fertilization-weed-control',
      'service-yard-cleanup',
      'commercial-property-services',
      'our-work',
      'article-how-often-to-mow-lawn-iowa',
      'contact',
    ],
  }),
  defineRoute({
    id: 'service-aeration-overseeding',
    path: '/services/aeration-overseeding',
    pageType: 'service',
    parentId: 'services',
    primaryKeyword: 'lawn aeration des moines ia',
    secondaryKeywords: [
      'aeration service Des Moines',
      'lawn seeding Des Moines',
      'overseeding Des Moines',
      'core aeration Des Moines',
      'aeration and seeding Des Moines',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Lawn Aeration & Seeding in Des Moines, IA | Mo's Lawn Care",
    h1: 'Lawn Aeration & Seeding in Des Moines, IA',
    description:
      "Improve thin or compacted lawns with aeration and seeding services in Des Moines, IA. See how Mo's can help and request a free property estimate.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: [
      'home',
      'services',
      'service-lawn-mowing',
      'service-fertilization-weed-control',
      'article-when-to-aerate-lawn-iowa',
      'article-best-time-to-overseed-lawn-iowa',
    ],
    outboundLinkIds: [
      'service-fertilization-weed-control',
      'service-lawn-mowing',
      'service-spring-cleanup',
      'services',
      'article-when-to-aerate-lawn-iowa',
      'article-best-time-to-overseed-lawn-iowa',
      'contact',
    ],
  }),
  defineRoute({
    id: 'service-fertilization-weed-control',
    path: '/services/fertilization-weed-control',
    pageType: 'service',
    parentId: 'services',
    primaryKeyword: 'lawn fertilization des moines ia',
    secondaryKeywords: [
      'weed control Des Moines',
      'lawn weed control Des Moines',
      'fertilization service Des Moines',
      'lawn treatment Des Moines',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Fertilization & Weed Control in Des Moines, IA | Mo's Lawn Care",
    h1: 'Lawn Fertilization & Weed Control in Des Moines, IA',
    description:
      "Professional lawn fertilization and weed control in Des Moines, IA for healthier, cleaner-looking turf. Request a free estimate from Mo's Lawn Care.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['home', 'services', 'service-lawn-mowing', 'service-aeration-overseeding'],
    outboundLinkIds: ['service-aeration-overseeding', 'service-lawn-mowing', 'services', 'contact'],
  }),
  defineRoute({
    id: 'service-landscaping',
    path: '/services/landscaping',
    pageType: 'service',
    parentId: 'services',
    primaryKeyword: 'landscaping des moines ia',
    secondaryKeywords: [
      'landscaping services Des Moines',
      'landscaping company Des Moines',
      'residential landscaping Des Moines',
      'landscape maintenance Des Moines',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Landscaping Services in Des Moines, IA | Mo's Lawn Care",
    h1: 'Landscaping Services in Des Moines, IA',
    description:
      "Upgrade and maintain your outdoor space with landscaping services in Des Moines, IA. View Mo's work and request a free residential or commercial estimate.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['home', 'services', 'service-flower-bed-maintenance', 'service-yard-cleanup'],
    outboundLinkIds: [
      'service-flower-bed-maintenance',
      'service-grading',
      'service-yard-cleanup',
      'our-work',
      'commercial-property-services',
      'contact',
    ],
  }),
  defineRoute({
    id: 'service-flower-bed-maintenance',
    path: '/services/flower-bed-maintenance',
    pageType: 'service',
    parentId: 'services',
    primaryKeyword: 'flower bed maintenance des moines',
    secondaryKeywords: [
      'landscape bed maintenance Des Moines',
      'flower bed cleanup Des Moines',
      'garden bed maintenance Des Moines',
      'bed cleanup Des Moines',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Flower Bed Maintenance in Des Moines, IA | Mo's Lawn Care",
    h1: 'Flower Bed Maintenance in Des Moines, IA',
    description:
      "Keep flower beds clean and maintained with professional bed care in Des Moines, IA. Request a free estimate from Mo's Lawn Care for your property.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['home', 'services', 'service-landscaping', 'service-spring-cleanup'],
    outboundLinkIds: [
      'service-landscaping',
      'service-spring-cleanup',
      'service-fall-cleanup-leaf-removal',
      'service-yard-cleanup',
      'contact',
    ],
  }),
  defineRoute({
    id: 'service-yard-cleanup',
    path: '/services/yard-cleanup',
    pageType: 'service',
    parentId: 'services',
    primaryKeyword: 'yard cleanup des moines ia',
    secondaryKeywords: [
      'yard cleanup service Des Moines',
      'overgrown yard cleanup Des Moines',
      'property cleanup Des Moines',
      'ground clearance Des Moines',
      'overgrown lawn cleanup Des Moines',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Yard Cleanup Service in Des Moines, IA | Mo's Lawn Care",
    h1: 'Yard Cleanup Service in Des Moines, IA',
    description:
      "Get overgrown yards and outdoor areas back under control with professional yard cleanup in Des Moines, IA. Contact Mo's for a free property estimate.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: [
      'home',
      'services',
      'service-lawn-mowing',
      'service-landscaping',
      'service-flower-bed-maintenance',
      'service-spring-cleanup',
      'service-fall-cleanup-leaf-removal',
      'service-grading',
    ],
    outboundLinkIds: [
      'service-lawn-mowing',
      'service-spring-cleanup',
      'service-fall-cleanup-leaf-removal',
      'service-grading',
      'service-landscaping',
      'contact',
    ],
  }),
  defineRoute({
    id: 'service-spring-cleanup',
    path: '/services/spring-cleanup',
    pageType: 'service',
    parentId: 'services',
    primaryKeyword: 'spring cleanup des moines ia',
    secondaryKeywords: [
      'spring yard cleanup Des Moines',
      'spring lawn cleanup Des Moines',
      'seasonal yard cleanup Des Moines',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Spring Yard Cleanup in Des Moines, IA | Mo's Lawn Care",
    h1: 'Spring Yard Cleanup in Des Moines, IA',
    description:
      "Prepare your property for the growing season with spring yard cleanup in Des Moines, IA. Request a free estimate from Mo's Lawn Care.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: [
      'home',
      'services',
      'service-aeration-overseeding',
      'service-flower-bed-maintenance',
      'service-yard-cleanup',
      'article-spring-lawn-cleanup-des-moines',
    ],
    outboundLinkIds: [
      'service-lawn-mowing',
      'service-flower-bed-maintenance',
      'service-yard-cleanup',
      'service-landscaping',
      'article-spring-lawn-cleanup-des-moines',
      'contact',
    ],
  }),
  defineRoute({
    id: 'service-fall-cleanup-leaf-removal',
    path: '/services/fall-cleanup-leaf-removal',
    pageType: 'service',
    parentId: 'services',
    primaryKeyword: 'leaf removal des moines ia',
    secondaryKeywords: [
      'fall cleanup Des Moines',
      'fall yard cleanup Des Moines',
      'leaf cleanup Des Moines',
      'leaf removal service Des Moines',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Fall Cleanup & Leaf Removal in Des Moines, IA | Mo's Lawn Care",
    h1: 'Fall Cleanup & Leaf Removal in Des Moines, IA',
    description:
      "Clear leaves and seasonal debris with fall cleanup and leaf removal in Des Moines, IA. Request a free estimate from Mo's Lawn Care.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: [
      'home',
      'services',
      'service-flower-bed-maintenance',
      'service-yard-cleanup',
      'article-fall-leaf-cleanup-des-moines',
    ],
    outboundLinkIds: [
      'service-yard-cleanup',
      'service-lawn-mowing',
      'service-snow-removal',
      'article-fall-leaf-cleanup-des-moines',
      'contact',
    ],
  }),
  defineRoute({
    id: 'service-grading',
    path: '/services/grading',
    pageType: 'service',
    parentId: 'services',
    primaryKeyword: 'yard grading des moines ia',
    secondaryKeywords: [
      'lawn grading Des Moines',
      'grading service Des Moines',
      'property grading Des Moines',
      'uneven yard grading Des Moines',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Yard Grading Service in Des Moines, IA | Mo's Lawn Care",
    h1: 'Yard Grading Services in Des Moines, IA',
    description:
      "Improve uneven ground and prepare outdoor areas with yard grading services in Des Moines, IA. Tell Mo's what your property needs and get a free estimate.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['home', 'services', 'service-landscaping', 'service-yard-cleanup'],
    outboundLinkIds: ['service-yard-cleanup', 'service-landscaping', 'our-work', 'contact'],
  }),
  defineRoute({
    id: 'service-snow-removal',
    path: '/services/snow-removal',
    pageType: 'service',
    parentId: 'services',
    primaryKeyword: 'snow removal des moines ia',
    secondaryKeywords: [
      'snow removal service Des Moines',
      'residential snow removal Des Moines',
      'commercial snow removal Des Moines',
      'driveway snow removal Des Moines',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Snow Removal Service in Des Moines, IA | Mo's Lawn Care",
    h1: 'Snow Removal Service in Des Moines, IA',
    description:
      "Reliable snow removal for residential and commercial properties in Des Moines, IA. Keep driveways and access areas clear with Mo's. Request an estimate.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: [
      'home',
      'services',
      'service-fall-cleanup-leaf-removal',
      'commercial-property-services',
      'reviews',
    ],
    outboundLinkIds: ['commercial-property-services', 'service-areas', 'reviews', 'contact'],
  }),
  defineRoute({
    id: 'commercial-property-services',
    path: '/commercial-property-services',
    pageType: 'commercial-index',
    parentId: 'home',
    primaryKeyword: 'commercial lawn care des moines ia',
    secondaryKeywords: [
      'commercial grounds maintenance Des Moines',
      'commercial property maintenance Des Moines',
      'commercial landscaping Des Moines',
      'commercial lawn service Des Moines',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Commercial Lawn Care in Des Moines, IA | Mo's Lawn Care",
    h1: 'Commercial Lawn Care & Property Services in Des Moines',
    description:
      "Commercial lawn care, cleanup, landscaping and snow removal for Des Moines properties. Build a dependable property maintenance plan with Mo's Lawn Care.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['home', 'services', 'service-lawn-mowing', 'service-landscaping', 'service-snow-removal'],
    outboundLinkIds: [
      'service-lawn-mowing',
      'service-aeration-overseeding',
      'service-fertilization-weed-control',
      'service-landscaping',
      'service-flower-bed-maintenance',
      'service-grading',
      'service-yard-cleanup',
      'service-spring-cleanup',
      'service-fall-cleanup-leaf-removal',
      'service-snow-removal',
      'our-work',
      'reviews',
      'service-areas',
      'contact',
    ],
  }),
  defineRoute({
    id: 'service-areas',
    path: '/service-areas',
    pageType: 'service-areas-index',
    parentId: 'home',
    primaryKeyword: 'lawn care des moines metro',
    secondaryKeywords: [
      'lawn care service areas Des Moines',
      'lawn care near Des Moines',
      'Des Moines metro lawn service',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Lawn Care Service Areas Near Des Moines, IA | Mo's Lawn Care",
    h1: 'Lawn Care Across the Des Moines Metro',
    description:
      "Mo's Lawn Care serves Des Moines, Ankeny, Waukee, Norwalk and Altoona with lawn care, landscaping, seasonal cleanups and snow removal.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['home', 'services', 'service-snow-removal', 'commercial-property-services'],
    outboundLinkIds: [
      'home',
      'service-area-ankeny',
      'service-area-waukee',
      'service-area-norwalk',
      'service-area-altoona',
      'services',
      'contact',
    ],
  }),
  defineRoute({
    id: 'service-area-ankeny',
    path: '/service-areas/ankeny-ia',
    pageType: 'service-area',
    parentId: 'service-areas',
    primaryKeyword: 'lawn care ankeny ia',
    secondaryKeywords: [
      'lawn service Ankeny IA',
      'lawn mowing Ankeny',
      'landscaping Ankeny',
      'yard cleanup Ankeny',
      'snow removal Ankeny',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Lawn Care in Ankeny, IA | Mo's Lawn Care",
    h1: 'Lawn Care Services in Ankeny, IA',
    description:
      'Professional lawn care in Ankeny, IA, including mowing, landscaping, seasonal cleanups, aeration, weed control and snow removal. Get a free estimate.',
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['home', 'service-areas'],
    outboundLinkIds: [
      'services',
      'service-lawn-mowing',
      'service-aeration-overseeding',
      'service-fertilization-weed-control',
      'service-landscaping',
      'service-yard-cleanup',
      'service-spring-cleanup',
      'service-fall-cleanup-leaf-removal',
      'service-grading',
      'service-snow-removal',
      'commercial-property-services',
      'service-areas',
      'home',
      'service-area-waukee',
      'service-area-norwalk',
      'service-area-altoona',
      'contact',
    ],
  }),
  defineRoute({
    id: 'service-area-waukee',
    path: '/service-areas/waukee-ia',
    pageType: 'service-area',
    parentId: 'service-areas',
    primaryKeyword: 'lawn care waukee ia',
    secondaryKeywords: [
      'lawn service Waukee IA',
      'lawn mowing Waukee',
      'landscaping Waukee',
      'yard cleanup Waukee',
      'snow removal Waukee',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Lawn Care in Waukee, IA | Mo's Lawn Care",
    h1: 'Lawn Care Services in Waukee, IA',
    description:
      'Professional lawn care in Waukee, IA, including mowing, landscaping, seasonal cleanups, aeration, weed control and snow removal. Get a free estimate.',
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['home', 'service-areas'],
    outboundLinkIds: [
      'services',
      'service-lawn-mowing',
      'service-aeration-overseeding',
      'service-fertilization-weed-control',
      'service-landscaping',
      'service-yard-cleanup',
      'service-spring-cleanup',
      'service-fall-cleanup-leaf-removal',
      'service-grading',
      'service-snow-removal',
      'commercial-property-services',
      'service-areas',
      'home',
      'service-area-ankeny',
      'service-area-norwalk',
      'service-area-altoona',
      'contact',
    ],
  }),
  defineRoute({
    id: 'service-area-norwalk',
    path: '/service-areas/norwalk-ia',
    pageType: 'service-area',
    parentId: 'service-areas',
    primaryKeyword: 'lawn care norwalk ia',
    secondaryKeywords: [
      'lawn service Norwalk IA',
      'lawn mowing Norwalk',
      'landscaping Norwalk',
      'yard cleanup Norwalk',
      'snow removal Norwalk',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Lawn Care in Norwalk, IA | Mo's Lawn Care",
    h1: 'Lawn Care Services in Norwalk, IA',
    description:
      'Professional lawn care in Norwalk, IA, including mowing, landscaping, seasonal cleanups, aeration, weed control and snow removal. Get a free estimate.',
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['home', 'service-areas'],
    outboundLinkIds: [
      'services',
      'service-lawn-mowing',
      'service-aeration-overseeding',
      'service-fertilization-weed-control',
      'service-landscaping',
      'service-yard-cleanup',
      'service-spring-cleanup',
      'service-fall-cleanup-leaf-removal',
      'service-grading',
      'service-snow-removal',
      'commercial-property-services',
      'service-areas',
      'home',
      'service-area-ankeny',
      'service-area-waukee',
      'service-area-altoona',
      'contact',
    ],
  }),
  defineRoute({
    id: 'service-area-altoona',
    path: '/service-areas/altoona-ia',
    pageType: 'service-area',
    parentId: 'service-areas',
    primaryKeyword: 'lawn care altoona ia',
    secondaryKeywords: [
      'lawn service Altoona IA',
      'lawn mowing Altoona',
      'landscaping Altoona',
      'yard cleanup Altoona',
      'snow removal Altoona',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Lawn Care in Altoona, IA | Mo's Lawn Care",
    h1: 'Lawn Care Services in Altoona, IA',
    description:
      'Professional lawn care in Altoona, IA, including mowing, landscaping, seasonal cleanups, aeration, weed control and snow removal. Get a free estimate.',
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['home', 'service-areas'],
    outboundLinkIds: [
      'services',
      'service-lawn-mowing',
      'service-aeration-overseeding',
      'service-fertilization-weed-control',
      'service-landscaping',
      'service-yard-cleanup',
      'service-spring-cleanup',
      'service-fall-cleanup-leaf-removal',
      'service-grading',
      'service-snow-removal',
      'commercial-property-services',
      'service-areas',
      'home',
      'service-area-ankeny',
      'service-area-waukee',
      'service-area-norwalk',
      'contact',
    ],
  }),
  defineRoute({
    id: 'about',
    path: '/about',
    pageType: 'about',
    parentId: 'home',
    primaryKeyword: "mo's lawn care des moines",
    secondaryKeywords: [
      'lawn care company Des Moines',
      'local lawn care company Des Moines',
      "Mo's Lawn Care Iowa",
    ],
    secondaryKeywordStatus: 'defined',
    title: "About Mo's Lawn Care | Des Moines, IA",
    h1: "About Mo's Lawn Care",
    description:
      "Learn about Mo's Lawn Care and Snow Removal Services LLC, the team helping residential and commercial properties across the Des Moines metro.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['home', 'contact'],
    outboundLinkIds: ['services', 'service-areas', 'our-work', 'reviews', 'contact'],
  }),
  defineRoute({
    id: 'our-work',
    path: '/our-work',
    pageType: 'work-index',
    parentId: 'home',
    primaryKeyword: 'lawn care projects des moines',
    secondaryKeywords: [
      'landscaping projects Des Moines',
      'lawn care before and after Des Moines',
      'lawn care gallery Des Moines',
      'yard cleanup before after',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Lawn Care & Landscaping Projects in Des Moines | Mo's",
    h1: 'Lawn Care & Landscaping Work Across the Des Moines Metro',
    description:
      "See lawn care, landscaping, cleanup and snow removal work from Mo's across the Des Moines metro, including before-and-after property transformations.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: [
      'home',
      'service-lawn-mowing',
      'service-landscaping',
      'service-grading',
      'commercial-property-services',
    ],
    outboundLinkIds: ['services', 'reviews', 'contact'],
  }),
  defineRoute({
    id: 'reviews',
    path: '/reviews',
    pageType: 'reviews-index',
    parentId: 'home',
    primaryKeyword: "mo's lawn care reviews",
    secondaryKeywords: [
      'lawn care reviews Des Moines',
      "Mo's Lawn Care Des Moines reviews",
      'snow removal reviews Des Moines',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Mo's Lawn Care Reviews | Des Moines, IA",
    h1: "What Customers Say About Mo's Lawn Care",
    description:
      "Read customer feedback about Mo's Lawn Care and Snow Removal Services LLC in the Des Moines metro, from mowing and cleanup to snow removal.",
    implementationStatus: 'implemented',
    publicationStatus: 'published',
    indexability: 'indexable',
    inboundLinkIds: ['home', 'service-snow-removal', 'commercial-property-services', 'our-work'],
    outboundLinkIds: ['services', 'our-work', 'contact'],
  }),
  defineRoute({
    id: 'contact',
    path: '/contact',
    pageType: 'contact',
    parentId: 'home',
    primaryKeyword: 'lawn care estimate des moines',
    secondaryKeywords: [
      'lawn care quote Des Moines',
      'free lawn estimate Des Moines',
      "contact Mo's Lawn Care",
    ],
    secondaryKeywordStatus: 'defined',
    title: "Contact Mo's Lawn Care | Free Estimate in Des Moines, IA",
    h1: 'Request a Free Property Estimate',
    description:
      "Tell Mo's Lawn Care what your Des Moines-area property needs. Request a free estimate for mowing, landscaping, cleanup, lawn treatments or snow removal.",
    ...plannedRouteState,
    inboundLinkIds: [
      'home',
      'services',
      'commercial-property-services',
      'service-areas',
      'about',
      'our-work',
      'reviews',
      'blog',
    ],
    outboundLinkIds: ['services', 'service-areas'],
  }),
  defineRoute({
    id: 'blog',
    path: '/blog',
    pageType: 'blog-index',
    parentId: 'home',
    primaryKeyword: 'iowa lawn care tips',
    secondaryKeywords: [
      'lawn care tips Des Moines',
      'Central Iowa lawn care guide',
      'seasonal lawn care Iowa',
      'Iowa yard care tips',
    ],
    secondaryKeywordStatus: 'defined',
    title: "Iowa Lawn Care Tips & Seasonal Guides | Mo's Lawn Care",
    h1: 'Lawn Care Tips for Des Moines & Central Iowa',
    description:
      'Practical lawn care and seasonal property tips for Des Moines and Central Iowa, including mowing, aeration, overseeding, cleanup and year-round planning.',
    ...plannedRouteState,
    inboundLinkIds: ['home'],
    outboundLinkIds: [
      'article-when-to-aerate-lawn-iowa',
      'article-best-time-to-overseed-lawn-iowa',
      'article-how-often-to-mow-lawn-iowa',
      'article-spring-lawn-cleanup-des-moines',
      'article-fall-leaf-cleanup-des-moines',
      'article-central-iowa-lawn-care-calendar',
    ],
  }),
  defineRoute({
    id: 'article-when-to-aerate-lawn-iowa',
    path: '/blog/when-to-aerate-lawn-iowa',
    pageType: 'blog-article',
    parentId: 'blog',
    primaryKeyword: 'when to aerate lawn in iowa',
    secondaryKeywords: [],
    secondaryKeywordStatus: 'pending-research',
    title: "When to Aerate Your Lawn in Iowa | Mo's Lawn Care",
    h1: 'When Is the Best Time to Aerate a Lawn in Iowa?',
    description:
      'Learn when Iowa lawns generally benefit from aeration, what signs to watch for and how aeration fits into a practical Central Iowa lawn care plan.',
    ...plannedRouteState,
    inboundLinkIds: ['blog', 'service-aeration-overseeding', 'article-central-iowa-lawn-care-calendar'],
    outboundLinkIds: [
      'service-aeration-overseeding',
      'article-central-iowa-lawn-care-calendar',
      'article-best-time-to-overseed-lawn-iowa',
    ],
  }),
  defineRoute({
    id: 'article-best-time-to-overseed-lawn-iowa',
    path: '/blog/best-time-to-overseed-lawn-iowa',
    pageType: 'blog-article',
    parentId: 'blog',
    primaryKeyword: 'best time to overseed lawn in iowa',
    secondaryKeywords: [],
    secondaryKeywordStatus: 'pending-research',
    title: "Best Time to Overseed a Lawn in Iowa | Mo's Lawn Care",
    h1: 'What Is the Best Time to Overseed a Lawn in Iowa?',
    description:
      'Understand the usual timing considerations for overseeding an Iowa lawn, how weather affects planning and when professional help may make sense.',
    ...plannedRouteState,
    inboundLinkIds: ['blog', 'service-aeration-overseeding', 'article-central-iowa-lawn-care-calendar'],
    outboundLinkIds: [
      'service-aeration-overseeding',
      'article-central-iowa-lawn-care-calendar',
      'article-when-to-aerate-lawn-iowa',
    ],
  }),
  defineRoute({
    id: 'article-how-often-to-mow-lawn-iowa',
    path: '/blog/how-often-to-mow-lawn-iowa',
    pageType: 'blog-article',
    parentId: 'blog',
    primaryKeyword: 'how often to mow lawn in iowa',
    secondaryKeywords: [],
    secondaryKeywordStatus: 'pending-research',
    title: "How Often Should You Mow a Lawn in Iowa? | Mo's Lawn Care",
    h1: 'How Often Should You Mow Your Lawn in Iowa?',
    description:
      'Learn what determines mowing frequency for Iowa lawns, including growth, weather and seasonal conditions, without relying on a rigid schedule.',
    ...plannedRouteState,
    inboundLinkIds: ['blog', 'service-lawn-mowing', 'article-central-iowa-lawn-care-calendar'],
    outboundLinkIds: ['service-lawn-mowing', 'article-central-iowa-lawn-care-calendar'],
  }),
  defineRoute({
    id: 'article-spring-lawn-cleanup-des-moines',
    path: '/blog/spring-lawn-cleanup-des-moines',
    pageType: 'blog-article',
    parentId: 'blog',
    primaryKeyword: 'spring lawn cleanup checklist des moines',
    secondaryKeywords: [],
    secondaryKeywordStatus: 'pending-research',
    title: "Spring Lawn Cleanup Checklist for Des Moines Properties | Mo's",
    h1: 'A Spring Lawn Cleanup Checklist for Des Moines Properties',
    description:
      'Use this practical spring cleanup checklist to prepare a Des Moines-area yard for the growing season and identify when professional cleanup can help.',
    ...plannedRouteState,
    inboundLinkIds: ['blog', 'service-spring-cleanup', 'article-central-iowa-lawn-care-calendar'],
    outboundLinkIds: ['service-spring-cleanup', 'article-central-iowa-lawn-care-calendar'],
  }),
  defineRoute({
    id: 'article-fall-leaf-cleanup-des-moines',
    path: '/blog/fall-leaf-cleanup-des-moines',
    pageType: 'blog-article',
    parentId: 'blog',
    primaryKeyword: 'fall leaf cleanup tips des moines',
    secondaryKeywords: [],
    secondaryKeywordStatus: 'pending-research',
    title: "Fall Leaf Cleanup Tips for Des Moines Properties | Mo's",
    h1: 'Fall Leaf Cleanup Tips for Des Moines Properties',
    description:
      'Plan fall leaf cleanup for a Des Moines-area property with practical timing, organization and disposal considerations for the season.',
    ...plannedRouteState,
    inboundLinkIds: [
      'blog',
      'service-fall-cleanup-leaf-removal',
      'article-central-iowa-lawn-care-calendar',
    ],
    outboundLinkIds: ['service-fall-cleanup-leaf-removal', 'article-central-iowa-lawn-care-calendar'],
  }),
  defineRoute({
    id: 'article-central-iowa-lawn-care-calendar',
    path: '/blog/central-iowa-lawn-care-calendar',
    pageType: 'blog-article',
    parentId: 'blog',
    primaryKeyword: 'central iowa lawn care calendar',
    secondaryKeywords: [],
    secondaryKeywordStatus: 'pending-research',
    title: "Central Iowa Lawn Care Calendar | Mo's Lawn Care",
    h1: 'A Seasonal Lawn Care Calendar for Central Iowa',
    description:
      'Plan mowing, cleanup, aeration and other lawn-care decisions through the seasons with a practical Central Iowa property-care calendar.',
    ...plannedRouteState,
    inboundLinkIds: [
      'blog',
      'article-when-to-aerate-lawn-iowa',
      'article-best-time-to-overseed-lawn-iowa',
      'article-how-often-to-mow-lawn-iowa',
      'article-spring-lawn-cleanup-des-moines',
      'article-fall-leaf-cleanup-des-moines',
    ],
    outboundLinkIds: [
      'article-when-to-aerate-lawn-iowa',
      'article-best-time-to-overseed-lawn-iowa',
      'article-how-often-to-mow-lawn-iowa',
      'article-spring-lawn-cleanup-des-moines',
      'article-fall-leaf-cleanup-des-moines',
      'service-lawn-mowing',
      'service-aeration-overseeding',
      'service-spring-cleanup',
      'service-fall-cleanup-leaf-removal',
    ],
  }),
] as const satisfies readonly CanonicalRoute[]

export const routesById = Object.fromEntries(routeRegistry.map((route) => [route.id, route])) as Record<
  (typeof routeRegistry)[number]['id'],
  (typeof routeRegistry)[number]
>

export const routeLabels = {
  home: 'Home',
  services: 'Services',
  'service-lawn-mowing': 'Lawn Mowing',
  'service-aeration-overseeding': 'Aeration & Seeding',
  'service-fertilization-weed-control': 'Fertilization & Weed Control',
  'service-landscaping': 'Landscaping',
  'service-flower-bed-maintenance': 'Flower Bed Maintenance',
  'service-yard-cleanup': 'Yard Cleanup',
  'service-spring-cleanup': 'Spring Cleanup',
  'service-fall-cleanup-leaf-removal': 'Fall Cleanup & Leaf Removal',
  'service-grading': 'Grading',
  'service-snow-removal': 'Snow Removal',
  'commercial-property-services': 'Commercial Property Services',
  'service-areas': 'Service Areas',
  'service-area-ankeny': 'Ankeny',
  'service-area-waukee': 'Waukee',
  'service-area-norwalk': 'Norwalk',
  'service-area-altoona': 'Altoona',
  about: 'About',
  'our-work': 'Our Work',
  reviews: 'Reviews',
  contact: 'Contact',
  blog: 'Lawn Care Tips',
  'article-when-to-aerate-lawn-iowa': 'When to Aerate a Lawn in Iowa',
  'article-best-time-to-overseed-lawn-iowa': 'When to Overseed a Lawn in Iowa',
  'article-how-often-to-mow-lawn-iowa': 'How Often to Mow a Lawn in Iowa',
  'article-spring-lawn-cleanup-des-moines': 'Spring Lawn Cleanup Checklist',
  'article-fall-leaf-cleanup-des-moines': 'Fall Leaf Cleanup Tips',
  'article-central-iowa-lawn-care-calendar': 'Central Iowa Lawn Care Calendar',
} as const satisfies Readonly<Record<RouteId, string>>

export const primaryNavigationRouteIds = [
  'services',
  'service-areas',
  'our-work',
  'reviews',
  'blog',
  'about',
  'contact',
] as const satisfies readonly RouteId[]

export const serviceNavigationRouteIds = [
  'service-lawn-mowing',
  'service-aeration-overseeding',
  'service-fertilization-weed-control',
  'service-landscaping',
  'service-flower-bed-maintenance',
  'service-yard-cleanup',
  'service-spring-cleanup',
  'service-fall-cleanup-leaf-removal',
  'service-grading',
  'service-snow-removal',
] as const satisfies readonly RouteId[]

export const footerServiceNavigationRouteIds = [
  'service-lawn-mowing',
  'service-aeration-overseeding',
  'service-fertilization-weed-control',
  'service-landscaping',
  'service-yard-cleanup',
  'service-spring-cleanup',
  'service-fall-cleanup-leaf-removal',
  'service-grading',
  'service-snow-removal',
] as const satisfies readonly RouteId[]

export const serviceAreaNavigationRouteIds = [
  'home',
  'service-area-ankeny',
  'service-area-waukee',
  'service-area-norwalk',
  'service-area-altoona',
] as const satisfies readonly RouteId[]

export const companyNavigationRouteIds = [
  'about',
  'our-work',
  'reviews',
  'blog',
  'contact',
] as const satisfies readonly RouteId[]

function resolveNavigationRoutes<const T extends readonly RouteId[]>(ids: T) {
  return ids.map((id) => ({
    id,
    label: routeLabels[id],
    href: routesById[id].path,
  }))
}

export const primaryNavigationRoutes = resolveNavigationRoutes(primaryNavigationRouteIds)
export const serviceNavigationRoutes = resolveNavigationRoutes(serviceNavigationRouteIds)
export const footerServiceNavigationRoutes = resolveNavigationRoutes(
  footerServiceNavigationRouteIds,
)
export const serviceAreaNavigationRoutes = serviceAreaNavigationRouteIds.map((id) => ({
  id,
  label: id === 'home' ? 'Des Moines' : routeLabels[id],
  href: routesById[id].path,
}))
export const companyNavigationRoutes = resolveNavigationRoutes(companyNavigationRouteIds)

export type BreadcrumbItem = Readonly<{
  routeId: RouteId
  label: string
  href: string
  isCurrent: boolean
}>

export function getBreadcrumbItems(routeId: RouteId): readonly BreadcrumbItem[] {
  const hierarchy: RouteId[] = []
  let currentId: RouteId | null = routeId

  while (currentId) {
    hierarchy.unshift(currentId)
    currentId = routesById[currentId].parentId
  }

  return hierarchy.map((id, index) => ({
    routeId: id,
    label: routeLabels[id],
    href: routesById[id].path,
    isCurrent: index === hierarchy.length - 1,
  }))
}
